language: java
before_script:
  - psql -c 'create database DataBaseForShopService' -U postgres
git:
  depth: 3
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
services:
  - postgresql
